%YAML:1.0

# ------------------------------------------------------------------------------------------
# Camera parameters
# ------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 703.269
Camera.fy: 701.809
Camera.cx: 307.127
Camera.cy: 237.118

Camera.k1: 0.103039
Camera.k2: -0.759932
Camera.p1: 0.001632
Camera.p2: -0.005473

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1